apiVersion: apps/v1
kind: Deployment
metadata:
  name: 4g-pcrf
spec:
  selector:
    matchLabels:
      app: pcrf-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: pcrf-deployment
    spec:
      containers:
        - name: pcrf-pod
          image: robjspencer/endccore:latest
          env:
            - name: MONGODB_HOSTNAME
              value: mongodb-service
            - name: PGW_HOSTNAME
              value: "pgw-diameter-service"
            - name: LD_LIBRARY_PATH
              value: "/usr/lib/x86_64-linux-gnu/5giccore/freeDiameter"
          command: ["/usr/bin/pcrf.sh"]
          ports:
            - name: pcrf-port
              containerPort: 3868
      initContainers:
      - name: mongodb-to-start-first
        image: busybox
        command: ["sh", "-c", "until nslookup mongodb-service; do echo Letting mongoDB to start first; sleep 2; done;"]

---

apiVersion: v1
kind: Service
metadata:
  name: pcrf-service
spec:
  selector:
    app: pcrf-deployment
  ports:
    - name: pcrf-port
      protocol: TCP
      port: 3868
      targetPort: 3868
  type: NodePort